title: Introduction to Programming for Public Policy (30550)
authors:
  EricPotash:
    name: Eric Potash
    display_name: Eric Potash
    email: epotash@uchicago.edu
    github: potash
description: "Class Syllabus"
google_analytics: 
show_downloads: true
#theme: jekyll-theme-minimal

#gems:
#  - jekyll-mentions
